In [1]:
import numpy as np

In [ ]:
test = np.loadtxt("./test.txt")
test.astype(int)
np.savetxt("./test.csv", test, delimiter=",")

#### ndarray

In [2]:
# dynamic typing을 지원하지 않는다. C로 실행된다. # dynamic typing : 실행 시점에서 타입을 결정
test_array = np.array(["1", "2", 3, 4], float)
test_array

array([1., 2., 3., 4.])

In [5]:
print(type(test_array))
print(type(test_array[0]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [16]:
test_array.dtype

dtype('float64')

In [17]:
test_array.shape

(4,)

In [13]:
from copy import deepcopy

In [14]:
a = [1,2,3]
b = deepcopy(a) # 값을 복사
a[0] = 4
print(a)
print(b)

[4, 2, 3]
[1, 2, 3]


In [2]:
matrix  = [[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(2, 4)

In [3]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [19]:
np.array(tensor, int).ndim

3

In [20]:
np.array(tensor, int).size

48

#### handling shape

In [23]:
np.array(matrix).reshape(2,2,2)

array([[[1, 2],
        [5, 8]],

       [[1, 2],
        [5, 8]]])

In [24]:
np.array(matrix).reshape(-1,2).shape # -1 : 갯수를 정확히 모를때 유동적으로 입력되도록 설정

(4, 2)

In [25]:
np.array(matrix).flatten()

array([1, 2, 5, 8, 1, 2, 5, 8])

#### indexing

In [27]:
np.array(matrix)[0][0] == np.array(matrix)[0,0]

True

In [61]:
a = np.array([1,3,0], float)
a

array([1., 3., 0.])

In [62]:
np.where(a>0, 1, 0) # R에서 ifelse와 같은 것.

array([1, 1, 0])

In [63]:
np.where(a>0) # R에서 where와 같은 것. index 반환

(array([0, 1], dtype=int64),)

In [64]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [65]:
np.isfinite(a)

array([ True, False, False])

In [70]:
a = np.array([1,2,5,8,74,26,19])
a

array([ 1,  2,  5,  8, 74, 26, 19])

In [71]:
np.argmax(a), np.argmin(a) # index 출력

(4, 0)

In [73]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 3, 3], dtype=int64), array([0, 0, 0, 0], dtype=int64))

#### boolean index

In [74]:
a = np.array([1,2,5,8,74,26,19])
a > 10

array([False, False, False, False,  True,  True,  True])

In [76]:
condition = a>10
a[condition]

array([74, 26, 19])

In [77]:
condition.astype(np.int)

array([0, 0, 0, 0, 1, 1, 1])

#### fancy index

In [78]:
a = np.array([1,2,3,4], float) # value
b = np.array([3,3,0,2], int) # index

In [79]:
a[b]

array([4., 4., 1., 3.])

In [80]:
a.take(b)

array([4., 4., 1., 3.])

In [81]:
a = np.array([[1,2], [3,4]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c] # a에서 (b, c)에  해당하는 값을 가져오기

array([1., 2., 4., 4., 2.])

#### slicing

In [29]:
np.array(matrix)[:,::2] # column을 처음부터 2씩 뛰어서

array([[1, 5],
       [1, 5]])

In [28]:
np.array(matrix)[::2,::3]

array([[1, 8]])

In [32]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
range(9)

range(0, 9)

In [40]:
np.arange(9).reshape(-1,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
np.arange(0, 9, 0.5).tolist()

[0.0,
 0.5,
 1.0,
 1.5,
 2.0,
 2.5,
 3.0,
 3.5,
 4.0,
 4.5,
 5.0,
 5.5,
 6.0,
 6.5,
 7.0,
 7.5,
 8.0,
 8.5]

In [46]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [47]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [49]:
np.empty(shape=(10,), dtype=np.int8) # garbage

array([ 39,  41,  32,  61,  61,  32,  73,  80, 118,  52], dtype=int8)

#### creation functions

In [4]:
test_matrix = np.arange(30).reshape(5,6)

In [5]:
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [6]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [7]:
np.empty_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [8]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [9]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [19]:
np.diag(matrix, k=1) # k : start index

array([1, 5])

In [20]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.53501618, 0.5844944 , 0.44053352, 0.37250713, 0.84108405],
       [0.11032306, 0.35889315, 0.40754411, 0.1989778 , 0.8750605 ]])

In [21]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 2.95422316,  0.19684437, -0.02982395,  1.41202419, -0.9188239 ],
       [ 1.47040537,  0.92455902,  1.24567123,  0.88577282, -0.23289184]])

#### operation functions

In [23]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
test_array.sum(axis=0), test_array.sum(axis=1)

(array([15, 18, 21, 24]), array([10, 26, 42]))

#### concatenate
* 작은 데이터에서의 concatenate는 numpy로 하면 오히려 느리다. 그냥 list로 작업하고 numpy로 변환할 것.

In [28]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [30]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [32]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [36]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
# array 기본적인 사직연산은 R에서와 같이 element-wise하게 실행된다.

In [39]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [41]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### broadcasting

In [42]:
scalar = 3
test_a + scalar

array([[4, 5, 6],
       [7, 8, 9]])

In [46]:
from PIL import Image
im = Image.open("broadcasting.jpg")
print(im.format, im.size, im.mode)

JPEG (1052, 692) RGB


In [48]:
im.show()

#### comparison

In [50]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [52]:
np.any(a>5), np.all(a>5)

(True, False)

In [53]:
np.logical_and(a>2, a<7)

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [59]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [60]:
c = np.array([True, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])