In [1]:
import numpy as np

#### ndarray

In [2]:
# dynamic typing을 지원하지 않는다. C로 실행된다. # dynamic typing : 실행 시점에서 타입을 결정
test_array = np.array(["1", "2", 3, 4], float)
test_array

array([1., 2., 3., 4.])

In [5]:
print(type(test_array))
print(type(test_array[0]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [16]:
test_array.dtype

dtype('float64')

In [17]:
test_array.shape

(4,)

In [13]:
from copy import deepcopy

In [14]:
a = [1,2,3]
b = deepcopy(a) # 값을 복사
a[0] = 4
print(a)
print(b)

[4, 2, 3]
[1, 2, 3]


In [22]:
matrix  = [[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(2, 4)

In [18]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [19]:
np.array(tensor, int).ndim

3

In [20]:
np.array(tensor, int).size

48

#### reshape

In [23]:
np.array(matrix).reshape(2,2,2)

array([[[1, 2],
        [5, 8]],

       [[1, 2],
        [5, 8]]])

In [24]:
np.array(matrix).reshape(-1,2).shape # -1 : 갯수를 정확히 모를때 유동적으로 입력되도록 설정

(4, 2)

#### flatten

In [25]:
np.array(matrix).flatten()

array([1, 2, 5, 8, 1, 2, 5, 8])

#### indexing

In [27]:
np.array(matrix)[0][0] == np.array(matrix)[0,0]

True

#### slicing

In [29]:
np.array(matrix)[:,::2] # column을 처음부터 2씩 뛰어서

array([[1, 5],
       [1, 5]])

In [28]:
np.array(matrix)[::2,::3]

array([[1, 8]])

In [32]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
range(9)

range(0, 9)

In [40]:
np.arange(9).reshape(-1,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
np.arange(0, 9, 0.5).tolist()

[0.0,
 0.5,
 1.0,
 1.5,
 2.0,
 2.5,
 3.0,
 3.5,
 4.0,
 4.5,
 5.0,
 5.5,
 6.0,
 6.5,
 7.0,
 7.5,
 8.0,
 8.5]

In [46]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [47]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [49]:
np.empty(shape=(10,), dtype=np.int8) # garbage

array([ 39,  41,  32,  61,  61,  32,  73,  80, 118,  52], dtype=int8)